{% set name = "fairly" %}
{% set version = "2.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/fairly-{{ version }}.tar.gz
  sha256: 0292751299ea1038bfafa524873cab4a8b3dc712829e4e09c5047abec846d535

build:
  entry_points:
    - fairly = fairly.cli:app
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 2

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - pip
  run:
    - python >={{ python_min }}
    - python-dateutil
    - requests
    - requests-toolbelt 
    - ruamel.yaml 
    - click

test:
  imports:
    - fairly
  requires:
    - pip
    - python {{ python_min }}
  commands:
    - pip check
    - fairly --help


about:
  home: https://github.com/ITC-CRIB/fairly
  summary: A package to create, publish, and download research datasets
  description: |
    Python package and CLI of the fairly toolset. It provides functionality for the core tasks of preparing, uploading and downloading datasets from research data repositories. 
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  doc_url: https://fairly.readthedocs.io
  dev_url: https://github.com/ITC-CRIB/fairly

extra:
  recipe-maintainers:
    - manuGil
