{% set name = "fairly" %}
{% set version = "1.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/fairly-{{ version }}.tar.gz
  sha256: d93b187f72215a059774134fcf862d51f9f5da687e8f058d208c1d87aa330e05

build:
  entry_points:
    - fairly = fairly.cli:app
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - hatch
    - pip
  run:
    - python >=3.8
    - python-dateutil
    - requests
    - requests-toolbelt >=1.0.0
    - ruamel.yaml >=0.17.26
    - typer >=0.9.0
    - rich

test:
  imports:
    - fairly
  requires:
    - pip
  commands:
    - pip check
    - fairly --help


about:
  home: https://github.com/ITC-CRIB/fairly
  summary: A package to create, publish, and download research datasets
  description: |
    Python package and CLI of the fairly toolset. It provides functionality for the core tasks of preparing, uploading and downloading datasets from research data repositories. The toolset currently provides integration with data repositories based on Invenio and Figshare.
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  doc_url: https://fairly.readthedocs.io
  dev_url: https://github.com/ITC-CRIB/fairly

extra:
  recipe-maintainers:
    - manuGil
